runtime: custom
env: flex
automatic_scaling:
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10
network:
  name: default